name: Go
on:
  release:
    types: [published]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        run: docker build --output=dist --target=final .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
